github:
  prebuilds:
    pullRequestsFromForks: true

vscode:
  extensions:
    - ms-vscode.makefile-tools
    - james-yu.latex-workshop
    - editorconfig.editorconfig

tasks:
  - before: sudo apt update && sudo apt install -y texlive texlive-latex-extra
  - before: pip install -U pip poetry
    init: poetry install
