#!/usr/bin/env python3

import sys
import locale
from _kosmorro.main import main

locale.setlocale(locale.LC_ALL, "")

if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        sys.exit(1)
