name: AppImage

on:
  pull_request:
    branches: [master, features]
  release:
    types: [published]

jobs:
  build-appimage:
    name: Build
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Prepare environment
        env:
          PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring
        run: |
          sudo apt install libfuse2
          pip install -U pip poetry appimage-builder
          poetry install
          sudo mkdir -p /usr/share/icons/hicolor/scalable/apps/kosmorro.svg
          sudo cp -r kosmorro/assets/svg/kosmorro-icon.svg /usr/share/icons/hicolor/scalable/apps/kosmorro.svg

      - name: Build wheel
        run: |
          make i18n build

      - name: Build AppImage
        run: |
          make appimage
          tree build

      - name: Upload AppImage
        uses: actions/upload-artifact@v2
        with:
          name: kosmorro.AppImage
          path: dist/kosmorro-latest-x86_64.AppImage

      - name: Upload AppImage version synchronization file
        uses: actions/upload-artifact@v2
        with:
          name: kosmorro.AppImage.zsync
          path: dist/kosmorro-latest-x86_64.AppImage.zsync

      - name: Run basic command
        run: |
          chmod +x dist/kosmorro-latest-x86_64.AppImage
          ./dist/kosmorro-latest-x86_64.AppImage
