name: Checks

on:
  push:
    branches: [master, features]
  pull_request:
    branches: [master, features]

jobs:
  lint:
    runs-on: ubuntu-latest

    name: Code Style
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-python@v6
      with:
        python-version: '3.x'
    - uses: psf/black@stable

  poetry-check:
    runs-on: ubuntu-latest

    name: Poetry
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      - run: |
          pip install -U pip poetry
          poetry install
      - run: poetry check --strict
