name: Commit lint

on:
  push:
    branches: [master, features]
  pull_request:
    branches: [master, features]

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install --upgrade pip comlipy
    - name: Lint
      run: |
        message="$(git log --format=%B -n 1 HEAD)"
        echo $message
        comlipy -c config-comlipy.yml "$message"

