name: Docker image

on:
  push:
    branches: [master, features]
  pull_request:
    branches: [master, features]

jobs:
  build-image:
    runs-on: ubuntu-latest

    name: Test building Docker image
    steps:
    - uses: actions/checkout@v1

    - name: Set up Docker
      uses: docker-practice/actions-setup-docker@v1

    - name: Create image
      run: |
        docker build -t kosmorro .

    - name: Execute image
      run: |
        docker run kosmorro kosmorro
