name: E2E tests

on:
  push:
    branches: [master, features]
  pull_request:
    branches: [master, features]

jobs:
  e2e-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-18.04
          - ubuntu-20.04
        python-version:
          - '3.7'
          - '3.8'
          - '3.9'

    name: E2E tests (Python ${{ matrix.python-version }} on ${{ matrix.os }})
    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Prepare tests
      run: |
        sudo apt update
        sudo apt install ruby
        sudo gem install ronn
        pip install -U setuptools pip requests wheel Babel

    - name: E2E tests
      run: |
        export ENVIRONMENT="CI"
        bash .scripts/tests-e2e.sh

    - name: manpage (section 1)
      run: |
        man -P $(which cat) kosmorro

    - name: manpage (section 7)
      run: |
        man -P $(which cat) 7 kosmorro
