name: Python Lint

on:
  push:
    branches: [master, features]
  pull_request:
    branches: [master, features]

jobs:
  pylint:
    runs-on: ubuntu-latest

    name: PyLint
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install --upgrade pip pipenv
        pipenv sync -d
    - name: Lint
      run: |
        pipenv run pylint kosmorro *.py kosmorrolib/*.py
