name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pipenv pylint-fail-under pylintfileheader
        pipenv sync -d
    - name: Lint
      run: |
        pylint-fail-under --fail_under 7.5 *.py
